import Foundation

// MARK: - 内置 CET-4 词库（30 个高频词）
// 固定 UUID 格式：11000000-0000-0000-0000-{12位数字}，保证每次启动 ID 不变，SM-2 记录可持续追踪

enum BuiltInWords {
    static let bookId = UUID(uuidString: "11000000-0000-0000-0000-000000000000")!

    static let wordBook = WordBook(
        id: bookId,
        name: "CET-4 高频词汇",
        level: "CET-4",
        description: "大学英语四级高频核心词汇，共 30 个精选单词",
        words: allWords,
        isBuiltIn: true,
        isEnabled: true
    )

    static let allWords: [Word] = [
        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000001")!,
              word: "abandon", phonetic: "/əˈbændən/", partOfSpeech: "v.",
              definitions: [.init(meaning: "放弃，抛弃",
                                  exampleEn: "She abandoned her plan to move abroad.",
                                  exampleZh: "她放弃了移居海外的计划。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000002")!,
              word: "ability", phonetic: "/əˈbɪlɪti/", partOfSpeech: "n.",
              definitions: [.init(meaning: "能力，才能",
                                  exampleEn: "He has the ability to learn quickly.",
                                  exampleZh: "他有快速学习的能力。")],
              difficulty: 1),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000003")!,
              word: "achieve", phonetic: "/əˈtʃiːv/", partOfSpeech: "v.",
              definitions: [.init(meaning: "实现，完成",
                                  exampleEn: "You can achieve your goals with hard work.",
                                  exampleZh: "努力就能实现你的目标。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000004")!,
              word: "admire", phonetic: "/ədˈmaɪər/", partOfSpeech: "v.",
              definitions: [.init(meaning: "钦佩，欣赏",
                                  exampleEn: "I truly admire your patience.",
                                  exampleZh: "我真的很钦佩你的耐心。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000005")!,
              word: "advance", phonetic: "/ədˈvɑːns/", partOfSpeech: "v./n.",
              definitions: [.init(meaning: "前进；进步",
                                  exampleEn: "Technology advances at an incredible speed.",
                                  exampleZh: "技术以惊人的速度进步。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000006")!,
              word: "adventure", phonetic: "/ədˈventʃər/", partOfSpeech: "n.",
              definitions: [.init(meaning: "冒险，奇遇",
                                  exampleEn: "Life is a great adventure.",
                                  exampleZh: "人生是一场伟大的冒险。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000007")!,
              word: "affect", phonetic: "/əˈfekt/", partOfSpeech: "v.",
              definitions: [.init(meaning: "影响",
                                  exampleEn: "Weather can greatly affect your mood.",
                                  exampleZh: "天气会极大地影响你的心情。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000008")!,
              word: "ambitious", phonetic: "/æmˈbɪʃəs/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "有雄心的，野心勃勃的",
                                  exampleEn: "She is ambitious and works very hard.",
                                  exampleZh: "她很有雄心，工作非常努力。")],
              difficulty: 3),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000009")!,
              word: "analyze", phonetic: "/ˈænəlaɪz/", partOfSpeech: "v.",
              definitions: [.init(meaning: "分析，研究",
                                  exampleEn: "Let's analyze the data more carefully.",
                                  exampleZh: "让我们更仔细地分析这些数据。")],
              difficulty: 3),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000010")!,
              word: "ancient", phonetic: "/ˈeɪnʃənt/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "古老的，古代的",
                                  exampleEn: "The ancient ruins were truly impressive.",
                                  exampleZh: "这些古老的遗址令人印象深刻。")],
              difficulty: 1),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000011")!,
              word: "anxious", phonetic: "/ˈæŋkʃəs/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "焦虑的，担忧的",
                                  exampleEn: "He felt anxious before the big exam.",
                                  exampleZh: "大考前他感到很焦虑。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000012")!,
              word: "approach", phonetic: "/əˈprəʊtʃ/", partOfSpeech: "v./n.",
              definitions: [.init(meaning: "接近；方法，途径",
                                  exampleEn: "Try a completely different approach.",
                                  exampleZh: "试试完全不同的方法。")],
              difficulty: 3),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000013")!,
              word: "atmosphere", phonetic: "/ˈætməsfɪər/", partOfSpeech: "n.",
              definitions: [.init(meaning: "氛围；大气层",
                                  exampleEn: "The restaurant had a very cozy atmosphere.",
                                  exampleZh: "这家餐厅氛围十分温馨。")],
              difficulty: 3),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000014")!,
              word: "attract", phonetic: "/əˈtrækt/", partOfSpeech: "v.",
              definitions: [.init(meaning: "吸引，引起…的注意",
                                  exampleEn: "Bright flowers attract bees and butterflies.",
                                  exampleZh: "鲜艳的花朵吸引蜜蜂和蝴蝶。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000015")!,
              word: "benefit", phonetic: "/ˈbenɪfɪt/", partOfSpeech: "n./v.",
              definitions: [.init(meaning: "好处，利益；受益",
                                  exampleEn: "Regular exercise has many health benefits.",
                                  exampleZh: "定期锻炼对健康有很多好处。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000016")!,
              word: "brilliant", phonetic: "/ˈbrɪljənt/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "聪明的；出色的；耀眼的",
                                  exampleEn: "She came up with a truly brilliant idea.",
                                  exampleZh: "她想出了一个非常出色的主意。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000017")!,
              word: "challenge", phonetic: "/ˈtʃælɪndʒ/", partOfSpeech: "n./v.",
              definitions: [.init(meaning: "挑战；向…挑战",
                                  exampleEn: "Every challenge is an opportunity to grow.",
                                  exampleZh: "每一次挑战都是成长的机会。")],
              difficulty: 1),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000018")!,
              word: "confident", phonetic: "/ˈkɒnfɪdənt/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "自信的，确信的",
                                  exampleEn: "Be confident in your own abilities.",
                                  exampleZh: "对自己的能力要有信心。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000019")!,
              word: "confuse", phonetic: "/kənˈfjuːz/", partOfSpeech: "v.",
              definitions: [.init(meaning: "使困惑，使迷乱",
                                  exampleEn: "The complex instructions confused everyone.",
                                  exampleZh: "复杂的说明让所有人都感到困惑。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000020")!,
              word: "creative", phonetic: "/kriˈeɪtɪv/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "有创造力的，创意十足的",
                                  exampleEn: "Children are naturally very creative.",
                                  exampleZh: "孩子天生具有很强的创造力。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000021")!,
              word: "curious", phonetic: "/ˈkjʊəriəs/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "好奇的，求知欲强的",
                                  exampleEn: "Curious minds always ask questions.",
                                  exampleZh: "好奇的人总是爱提问。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000022")!,
              word: "determine", phonetic: "/dɪˈtɜːmɪn/", partOfSpeech: "v.",
              definitions: [.init(meaning: "决定；确定；下定决心",
                                  exampleEn: "Your attitude determines your success.",
                                  exampleZh: "你的态度决定你的成败。")],
              difficulty: 3),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000023")!,
              word: "discover", phonetic: "/dɪˈskʌvər/", partOfSpeech: "v.",
              definitions: [.init(meaning: "发现，找到",
                                  exampleEn: "Scientists discover new species every year.",
                                  exampleZh: "科学家每年都会发现新物种。")],
              difficulty: 1),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000024")!,
              word: "effective", phonetic: "/ɪˈfektɪv/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "有效的，起作用的",
                                  exampleEn: "Exercise is an effective way to stay healthy.",
                                  exampleZh: "运动是保持健康的有效方式。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000025")!,
              word: "encourage", phonetic: "/ɪnˈkʌrɪdʒ/", partOfSpeech: "v.",
              definitions: [.init(meaning: "鼓励，激励",
                                  exampleEn: "Good teachers always encourage their students.",
                                  exampleZh: "好老师总是鼓励他们的学生。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000026")!,
              word: "essential", phonetic: "/ɪˈsenʃl/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "必不可少的，本质的",
                                  exampleEn: "Water is essential for all living things.",
                                  exampleZh: "水对一切生物来说都是必不可少的。")],
              difficulty: 3),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000027")!,
              word: "explore", phonetic: "/ɪkˈsplɔːr/", partOfSpeech: "v.",
              definitions: [.init(meaning: "探索，探险；调查",
                                  exampleEn: "Let's explore new possibilities together.",
                                  exampleZh: "让我们一起探索新的可能性。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000028")!,
              word: "familiar", phonetic: "/fəˈmɪliər/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "熟悉的，常见的",
                                  exampleEn: "This song sounds familiar to me.",
                                  exampleZh: "这首歌我听起来很熟悉。")],
              difficulty: 2),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000029")!,
              word: "flexible", phonetic: "/ˈfleksɪbl/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "灵活的，可弯曲的",
                                  exampleEn: "A flexible schedule helps boost productivity.",
                                  exampleZh: "灵活的日程安排有助于提高工作效率。")],
              difficulty: 3),

        .init(id: UUID(uuidString: "11000000-0000-0000-0000-000000000030")!,
              word: "grateful", phonetic: "/ˈɡreɪtfl/", partOfSpeech: "adj.",
              definitions: [.init(meaning: "感激的，感谢的",
                                  exampleEn: "I am truly grateful for your support.",
                                  exampleZh: "我真心感谢你的支持。")],
              difficulty: 2),
    ]
}
